version: '3'
services:
  ct_immd_nlp:
    image: ct-immd-nlp:v0.91
    ports:
      - "8080:8080"
    volumes:
      - /opt/email_classifier/nlp/data:/app/data/project
      - /opt/email_classifier/nlp/log:/app/log
      # - ./nfs-data:/app/nfs-data

    command: >
      bash -c "python nlp_pipeline.py"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           device_ids: [ '0' ]
    #           capabilities: [ gpu ]
